environment:
  matrix:
     - TARGET: x86_64-pc-windows-msvc
       CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - cinst opencv
  - dir C:\tools\opencv\build\x64\
  - set LIB=%lib%;C:\tools\opencv\build\x64\vc14\lib
  - set PATH=%path%;C:\tools\opencv\build\x64\vc14\bin

build: false

test_script:
 - cargo build --verbose
