[package]
name = "webcamrs"
version = "0.1.0"
authors = ["Junichi Kajiwara <junichi.kajiwara@gmail.com>"]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]

libc = "0.1"